//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_ChildAbuseGIS2013.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tasks.arcgisonline.com/ArcGIS/services/Geometry/GeometryServer")]
        public string FYP_ChildAbuseGIS2013_com_arcgisonline_tasks_Geometry_GeometryServer {
            get {
                return ((string)(this["FYP_ChildAbuseGIS2013_com_arcgisonline_tasks_Geometry_GeometryServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tasks.arcgisonline.com/ArcGIS/services/Geometry/GeometryServer")]
        public string FYP_ChildAbuseGIS2013_com_arcgisonline_tasks1_Geometry_GeometryServer {
            get {
                return ((string)(this["FYP_ChildAbuseGIS2013_com_arcgisonline_tasks1_Geometry_GeometryServer"]));
            }
        }
    }
}
